version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: market_tracker/Dockerfile
    expose:
      - "8000"  # Exposed internally
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    depends_on:
      - fastapi
    expose:
      - "8501"  # Exposed internally
    environment:
      - API_URL=http://fastapi:8000  # Internal communication with FastAPI
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Expose Streamlit publicly on port 80
    depends_on:
      - streamlit
    restart: always